#' Launch Manual Review Shiny App for Name Matching Candidates
#'
#' This function launches a Shiny interface for manually approving or rejecting
#' name matching candidates generated by `match_names_sbert()`. It displays candidates
#' from `match_result.csv` with checkboxes, supports bulk actions, and saves approved
#' pairs to `nayose_dict.csv` for future name matching.
#'
#' @return None. Launches the Shiny app; results are saved via manual operation.
#' @importFrom shiny fluidPage titlePanel sidebarLayout sidebarPanel sliderInput
#'   actionButton mainPanel DTOutput reactiveVal renderDT observeEvent shinyApp
#'   showNotification NS
#' @importFrom DT datatable renderDT dataTableProxy selectRows
#' @importFrom utils read.csv write.csv
#' @export
launch_nayose_app <- function() {
  ui <- shiny::fluidPage(
    shiny::titlePanel("Manual Review of Name Matching Candidates"),
    shiny::sidebarLayout(
      shiny::sidebarPanel(
        shiny::sliderInput("threshold", "Similarity Threshold", min = 0.5, max = 1, value = 0.75, step = 0.01),
        shiny::actionButton("select_all", "Select All"),
        shiny::actionButton("approve_selected", "Approve Selected"),
        shiny::actionButton("reject_selected", "Reject Selected"),
        shiny::actionButton("save_csv", "Save Approved Only")
      ),
      shiny::mainPanel(
        DT::DTOutput("table"),
        shiny::br(),
        DT::DTOutput("confirmed_table")
      )
    )
  )

  server <- function(input, output, session) {
    # Load initial data
    original_df <- utils::read.csv("match_result.csv", stringsAsFactors = FALSE)
    match_df <- shiny::reactiveVal(original_df)
    confirmed <- shiny::reactiveVal(data.frame(
      name_a = character(),
      name_b = character(),
      similarity = numeric(),
      status = character(),
      stringsAsFactors = FALSE
    ))

    # Display filtered table with multi-select
    output$table <- DT::renderDT({
      filtered <- match_df()[match_df()$similarity >= input$threshold, ]
      DT::datatable(filtered, selection = list(mode = "multiple"))
    })

    # Table proxy for selection control
    table_proxy <- DT::dataTableProxy("table")

    # Select all visible rows
    shiny::observeEvent(input$select_all, {
      filtered <- match_df()[match_df()$similarity >= input$threshold, ]
      DT::selectRows(table_proxy, seq_len(nrow(filtered)))
    })

    # Approve selected rows
    shiny::observeEvent(input$approve_selected, {
      rows <- input$table_rows_selected
      filtered <- match_df()[match_df()$similarity >= input$threshold, ]
      if (length(rows) > 0) {
        selected <- filtered[rows, ]
        selected$status <- "approved"
        confirmed(rbind(confirmed(), selected))

        updated <- match_df()
        for (i in seq_len(nrow(selected))) {
          updated <- updated[!(updated$name_a == selected$name_a[i] & updated$name_b == selected$name_b[i]), ]
        }
        match_df(updated)
      }
    })

    # Reject selected rows
    shiny::observeEvent(input$reject_selected, {
      rows <- input$table_rows_selected
      filtered <- match_df()[match_df()$similarity >= input$threshold, ]
      if (length(rows) > 0) {
        selected <- filtered[rows, ]
        selected$status <- "rejected"
        confirmed(rbind(confirmed(), selected))

        updated <- match_df()
        for (i in seq_len(nrow(selected))) {
          updated <- updated[!(updated$name_a == selected$name_a[i] & updated$name_b == selected$name_b[i]), ]
        }
        match_df(updated)
      }
    })

    # Save approved records only
    shiny::observeEvent(input$save_csv, {
      approved <- confirmed()[confirmed()$status == "approved", ]
      utils::write.csv(approved, "nayose_dict.csv", row.names = FALSE)
      shiny::showNotification("Approved records saved to nayose_dict.csv")
    })

    # Show confirmed results
    output$confirmed_table <- DT::renderDT({
      DT::datatable(confirmed())
    })
  }

  shiny::shinyApp(ui, server)
}
